import os
from datetime import datetime
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from loguru import logger
from dotenv import load_dotenv

# Load Environment Variables
load_dotenv()

from agents.student_assistant import student_assistant
from agents.faculty_assistant import faculty_assistant
from agents.admin_assistant import admin_assistant
from agents.rag_agent import rag_agent
from agents.memory_agent import memory_agent
from agents.timetable_agent import timetable_agent
from scheduler.optimizer import scheduler_optimizer
from scheduler.absence_adjuster import absence_adjuster
from tools.mysql_tools import mysql_tools
from tools.file_generator import timetable_file_generator
from rag.document_processor import document_processor
from rag.qdrant_manager import qdrant_manager
from memory.mongo_memory import mongo_memory

app = FastAPI(
    title="CSE Department AI Agentic Microservice",
    description="Cloud-Ready Multi-Agent Microservice powering AI Timetable Generation, Intelligent Teacher Scheduling, Qdrant Vector LTM/RAG, and MongoDB STM for the Computer Science & Engineering Department.",
    version="2.0.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----------------- Request Models -----------------
class ChatRequest(BaseModel):
    user_id: Optional[str] = Field(default="user_default", description="ID of student, faculty, hod, or admin")
    role: Optional[str] = Field(default="student", description="Role: student | faculty | hod | admin")
    prompt: Optional[str] = Field(default=None, description="User query text")
    message: Optional[str] = Field(default=None, description="Alternative field for user query text")
    conversation_id: Optional[str] = Field(default=None, description="Unique conversation thread ID")
    conversationId: Optional[str] = Field(default=None, description="Alternative field for conversation ID")
    agent: Optional[str] = Field(default=None, description="Specific targeted agent (e.g. 'timetable')")
    context_history: Optional[List[Dict[str, str]]] = Field(default=None, description="Recent conversation turns")

class GenerateTimetableRequest(BaseModel):
    department: str = Field(default="CSE")
    year: str = Field(default="3rd Year")
    semester: int = Field(default=5)
    section: str = Field(default="A")
    academic_year: str = Field(default="2026-27")
    custom_constraints: Optional[List[str]] = Field(default_factory=list)
    created_by: str = Field(default="AI Timetable Engine")

class AnalyzeAbsenceRequest(BaseModel):
    teacher_name: str = Field(..., description="Name or partial name of absent teacher")
    date: Optional[str] = Field(default=None, description="Date in YYYY-MM-DD format")
    day: Optional[str] = Field(default=None, description="Day name, e.g. Monday")
    department: str = Field(default="CSE")

class ApplySubstitutionRequest(BaseModel):
    absence_data: Dict[str, Any] = Field(..., description="Substitution proposal payload generated by /analyze")
    approved_by: str = Field(default="Dr. Alok Verma (HOD)")

class ExportTimetableRequest(BaseModel):
    department: str = Field(default="CSE")
    year: str = Field(default="3rd Year")
    semester: int = Field(default=5)
    section: str = Field(default="A")
    academic_year: str = Field(default="2026-27")
    version: int = Field(default=1)

class IndexDocumentRequest(BaseModel):
    noteId: Optional[int] = None
    filePath: str = Field(..., description="Absolute path to the uploaded document on disk")
    fileName: Optional[str] = None
    title: str = Field(..., description="Title of the academic document")
    category: str = Field(default="Notes")
    subjectId: Optional[int] = None
    year: Optional[str] = None
    semester: Optional[int] = None

class RAGSearchRequest(BaseModel):
    query: str = Field(..., description="Semantic search query")
    department: str = Field(default="CSE")
    collection: Optional[str] = Field(default=None)
    top_k: int = Field(default=4)

# ----------------- Routes -----------------

@app.get("/")
def root():
    return {
        "service": "CSE Department AI Agentic Microservice",
        "department": "Computer Science & Engineering",
        "status": "Online",
        "docs": "/docs",
        "vector_engine": "Qdrant Cloud / Embedded (768 Dimensions)",
        "long_term_memory": "Qdrant (erp_long_term_memory)",
        "document_rag": "Qdrant (erp_documents)",
        "scheduling_engine": "Deterministic Constraint Optimization Engine (CSP)",
        "memory": "MongoDB Short-Term Memory (STM)",
        "academic_source_of_truth": "MySQL"
    }

@app.get("/health")
def health_check():
    db_type, conn = mysql_tools._get_connection()
    mysql_active = conn is not None
    if conn:
        try:
            conn.close()
        except Exception:
            pass

    return {
        "status": "UP",
        "service": "FastAPI AI Microservice",
        "qdrant_status": "Ready",
        "qdrant_collections": ["erp_long_term_memory", "erp_documents", "Notes", "Circulars"],
        "mongo_status": "Ready" if mongo_memory.client else "Cache Mode",
        "mysql_status": f"Ready ({db_type})" if mysql_active else "Unavailable",
        "llm_provider": os.getenv("LLM_PROVIDER", "Groq / OpenAI Compatible"),
        "llm_configured": bool(os.getenv("GROQ_API_KEY") or os.getenv("LLM_API_KEY")),
        "active_agents": [
            "TimetableAgent",
            "TeacherSchedulerAgent",
            "FacultyAssistant",
            "AdminAssistant",
            "StudentAssistant",
            "RAGAgent",
            "MemoryAgent"
        ]
    }

@app.post("/ai/chat")
async def chat_endpoint(req: ChatRequest):
    """
    Central Multi-Agent Chat Entrypoint.
    Intelligently routes requests to TimetableAgent, FacultyAssistant, AdminAssistant, or StudentAssistant.
    """
    try:
        user_role = (req.role or "student").lower()
        query_text = (req.prompt or req.message or "").strip()
        conv_id = req.conversation_id or req.conversationId or f"conv_{int(datetime.utcnow().timestamp())}"
        target_agent = (req.agent or "").lower()

        if not query_text:
            raise HTTPException(status_code=400, detail="A message or prompt text is required.")

        # Save user message to MongoDB
        mongo_memory.save_message(
            conversation_id=conv_id,
            user_id=req.user_id,
            role=user_role,
            sender="user",
            content=query_text
        )

        query_lower = query_text.lower()
        is_timetable_query = (
            target_agent in ["timetable", "scheduler", "teacher_scheduler"] or
            user_role in ["hod"] or
            any(w in query_lower for w in ["timetable", "schedule", "absent", "leave", "adjust his classes", "adjust her classes", "adjust all his classes", "substitute", "make friday", "generate timetable"])
        )

        # Agent Routing
        if is_timetable_query:
            agent_result = timetable_agent.handle_request(
                prompt=query_text,
                user_id=req.user_id,
                conversation_id=conv_id,
                role=user_role,
                context_history=req.context_history
            )
        elif user_role in ["faculty", "teacher", "tg"]:
            agent_result = faculty_assistant.handle_query(
                prompt=query_text,
                user_id=req.user_id,
                conversation_id=conv_id,
                context_history=req.context_history
            )
        elif user_role == "admin":
            agent_result = admin_assistant.handle_query(
                prompt=query_text,
                user_id=req.user_id,
                conversation_id=conv_id,
                context_history=req.context_history
            )
        else: # Student
            agent_result = student_assistant.handle_query(
                prompt=query_text,
                user_id=req.user_id,
                conversation_id=conv_id,
                context_history=req.context_history
            )

        # Save assistant response to MongoDB
        mongo_memory.save_message(
            conversation_id=conv_id,
            user_id=req.user_id,
            role=user_role,
            sender="assistant",
            content=agent_result["answer"],
            citations=agent_result.get("citations", []),
            tool_calls=agent_result.get("tool_calls", [])
        )

        return {
            "success": True,
            "conversation_id": conv_id,
            "answer": agent_result["answer"],
            "detected_intent": agent_result.get("detected_intent", "GENERAL_QUERY"),
            "agent_used": agent_result.get("agent_used", "GeneralAgent"),
            "actions_taken": agent_result.get("actions_taken", []),
            "proposed_actions": agent_result.get("proposed_actions", []),
            "approval_requirement": agent_result.get("approval_requirement", {"requires_approval": False}),
            "generated_files": agent_result.get("generated_files", []),
            "affected_classes": agent_result.get("affected_classes", []),
            "conflicts": agent_result.get("conflicts", []),
            "citations": agent_result.get("citations", []),
            "timetable_data": agent_result.get("timetable_data", [])
        }
    except Exception as e:
        logger.error(f"[Chat Endpoint Error]: {e}")
        raise HTTPException(status_code=500, detail=f"AI Agent execution error: {str(e)}")

# ----------------- Dedicated Timetable & Scheduler API -----------------

@app.post("/ai/timetable/generate")
async def generate_timetable_api(req: GenerateTimetableRequest):
    """
    Deterministic Timetable Generator Endpoint:
    Queries authoritative MySQL tables -> executes CSP constraint optimizer -> saves new version in MySQL -> outputs XLSX & PDF.
    """
    try:
        subjects = mysql_tools.get_all_subjects(semester=req.semester, department=req.department)
        faculty_list = mysql_tools.get_all_faculty(department=req.department)
        rooms = mysql_tools.get_all_rooms(department=req.department)

        opt_res = scheduler_optimizer.generate_timetable(
            department=req.department,
            year=req.year,
            semester=req.semester,
            section=req.section,
            subjects=subjects,
            faculty_list=faculty_list,
            rooms=rooms,
            custom_constraints=req.custom_constraints
        )

        slots = opt_res.get("timetable_slots", [])
        metrics = opt_res.get("metrics", {})

        # Save to MySQL
        master_id = mysql_tools.save_new_timetable_version(
            department=req.department,
            year=req.year,
            semester=req.semester,
            section=req.section,
            academic_year=req.academic_year,
            slots=slots,
            stats=metrics,
            created_by=req.created_by
        )

        master_row = mysql_tools.get_timetable_master(req.semester, req.section, req.academic_year)
        version_num = master_row.get("version", 1) if master_row else 1

        excel_info = timetable_file_generator.generate_excel(
            req.department, req.year, req.semester, req.section, req.academic_year, version_num, slots, metrics
        )
        pdf_info = timetable_file_generator.generate_pdf(
            req.department, req.year, req.semester, req.section, req.academic_year, version_num, slots, metrics
        )

        return {
            "success": True,
            "master_id": master_id,
            "version": version_num,
            "department": req.department,
            "year": req.year,
            "semester": req.semester,
            "section": req.section,
            "slots_count": len(slots),
            "metrics": metrics,
            "conflicts": opt_res.get("conflicts", []),
            "files": {
                "excel": excel_info,
                "pdf": pdf_info
            },
            "slots": slots
        }
    except Exception as e:
        logger.error(f"[Generate Timetable API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/teacher-scheduler/analyze")
async def analyze_absence_api(req: AnalyzeAbsenceRequest):
    """
    Teacher Absence & Substitution Analysis Endpoint:
    Finds affected classes for absent faculty and ranks feasible substitutes deterministically.
    """
    try:
        res = absence_adjuster.analyze_and_propose(
            teacher_query=req.teacher_name,
            date_str=req.date,
            day_name=req.day,
            department=req.department
        )
        return res
    except Exception as e:
        logger.error(f"[Analyze Absence API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/teacher-scheduler/apply")
async def apply_substitutions_api(req: ApplySubstitutionRequest):
    """
    Applies approved substitution proposals transactionally into MySQL.
    """
    try:
        res = absence_adjuster.execute_approved_substitutions(
            absence_data=req.absence_data,
            approved_by=req.approved_by
        )
        return res
    except Exception as e:
        logger.error(f"[Apply Substitutions API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/timetable/export/excel")
async def export_excel_api(req: ExportTimetableRequest):
    slots = mysql_tools.get_timetable(year=req.year, semester=req.semester, section=req.section)
    res = timetable_file_generator.generate_excel(
        req.department, req.year, req.semester, req.section, req.academic_year, req.version, slots
    )
    return {"success": True, **res}

@app.post("/ai/timetable/export/pdf")
async def export_pdf_api(req: ExportTimetableRequest):
    slots = mysql_tools.get_timetable(year=req.year, semester=req.semester, section=req.section)
    res = timetable_file_generator.generate_pdf(
        req.department, req.year, req.semester, req.section, req.academic_year, req.version, slots
    )
    return {"success": True, **res}

# ----------------- Document RAG Indexing & Retrieval -----------------

@app.post("/ai/rag/index")
async def index_document_endpoint(req: IndexDocumentRequest):
    """
    Ingests document into Qdrant erp_documents with department isolation.
    """
    try:
        if not os.path.exists(req.filePath):
            raise HTTPException(status_code=404, detail=f"File not found on server: {req.filePath}")

        raw_text = document_processor.extract_text(req.filePath)
        if not raw_text or not raw_text.strip():
            raw_text = f"Title: {req.title}\nCategory: {req.category}\nDepartment: Computer Science & Engineering"

        metadata = {
            "title": req.title,
            "category": req.category,
            "note_id": req.noteId,
            "file_name": req.fileName or os.path.basename(req.filePath),
            "subject_id": req.subjectId,
            "year": req.year,
            "semester": req.semester,
            "department": "CSE"
        }
        chunks = document_processor.chunk_text(raw_text, metadata=metadata)
        count = qdrant_manager.index_document_chunks(collection_name="erp_documents", chunks=chunks)

        return {
            "success": True,
            "message": f"Successfully indexed {count} chunks into Qdrant 'erp_documents'.",
            "chunksIndexed": count,
            "collection": "erp_documents",
            "title": req.title
        }
    except Exception as e:
        logger.error(f"[RAG Index Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/rag/search")
async def rag_search_endpoint(req: RAGSearchRequest):
    """
    Performs hybrid retrieval against Qdrant erp_documents with department isolation.
    """
    try:
        results = qdrant_manager.search_rag(
            query=req.query,
            department=req.department,
            category=req.collection,
            top_k=req.top_k
        )
        return {
            "success": True,
            "query": req.query,
            "department": req.department,
            "results": results
        }
    except Exception as e:
        logger.error(f"[RAG Search Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
