import os
from datetime import datetime
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from loguru import logger
from dotenv import load_dotenv

# Load Environment Variables
load_dotenv()

from agents.student_assistant import student_assistant
from agents.faculty_assistant import faculty_assistant
from agents.admin_assistant import admin_assistant
from agents.rag_agent import rag_agent
from agents.memory_agent import memory_agent
from agents.timetable_agent import timetable_agent
from agents.orchestrator import central_orchestrator
from scheduler.optimizer import scheduler_optimizer
from scheduler.absence_adjuster import absence_adjuster
from tools.postgres_tools import postgres_tools
from tools.file_generator import timetable_file_generator
from rag.document_processor import document_processor
from rag.qdrant_manager import qdrant_manager
from memory.mongo_memory import mongo_memory
from llm.provider import llm_provider
from file_processing.file_type_router import file_type_router
from file_processing.imagekit_client import imagekit_client


app = FastAPI(
    title="CSE Department AI Agentic Microservice",
    description="Cloud-Ready Multi-Agent Microservice powering AI Timetable Generation, Intelligent Teacher Scheduling, Qdrant Vector LTM/RAG, and MongoDB STM for the Computer Science & Engineering Department.",
    version="2.0.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----------------- Request Models -----------------
class ChatRequest(BaseModel):
    user_id: Optional[str] = Field(default="user_default", description="ID of student, faculty, hod, or admin")
    role: Optional[str] = Field(default="student", description="Role: student | faculty | hod | admin")
    prompt: Optional[str] = Field(default=None, description="User query text")
    message: Optional[str] = Field(default=None, description="Alternative field for user query text")
    conversation_id: Optional[str] = Field(default=None, description="Unique conversation thread ID")
    conversationId: Optional[str] = Field(default=None, description="Alternative field for conversation ID")
    agent: Optional[str] = Field(default=None, description="Specific targeted agent (e.g. 'timetable')")
    context_history: Optional[List[Dict[str, str]]] = Field(default=None, description="Recent conversation turns")

class GenerateTimetableRequest(BaseModel):
    department: str = Field(default="CSE")
    year: str = Field(default="3rd Year")
    semester: int = Field(default=5)
    section: str = Field(default="A")
    academic_year: str = Field(default="2026-27")
    working_days: Optional[List[str]] = Field(default_factory=list)
    breaks: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
    custom_constraints: Optional[List[str]] = Field(default_factory=list)
    custom_subjects: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
    period_timings: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
    start_time: Optional[str] = Field(default="09:00 AM")
    period_duration_minutes: Optional[int] = Field(default=50)
    periods_per_day: Optional[int] = Field(default=7)
    created_by: str = Field(default="AI Timetable Engine")

class AnalyzeAbsenceRequest(BaseModel):
    teacher_name: str = Field(..., description="Name or partial name of absent teacher")
    date: Optional[str] = Field(default=None, description="Date in YYYY-MM-DD format")
    day: Optional[str] = Field(default=None, description="Day name, e.g. Monday")
    department: str = Field(default="CSE")

class ApplySubstitutionRequest(BaseModel):
    absence_data: Dict[str, Any] = Field(..., description="Substitution proposal payload generated by /analyze")
    approved_by: str = Field(default="Dr. Alok Verma (HOD)")

class ExportTimetableRequest(BaseModel):
    department: str = Field(default="CSE")
    year: str = Field(default="3rd Year")
    semester: int = Field(default=5)
    section: str = Field(default="A")
    academic_year: str = Field(default="2026-27")
    version: int = Field(default=1)

class IndexDocumentRequest(BaseModel):
    noteId: Optional[int] = None
    filePath: str = Field(..., description="Absolute path to the uploaded document on disk")
    fileName: Optional[str] = None
    title: str = Field(..., description="Title of the academic document")
    category: str = Field(default="Notes")
    subjectId: Optional[int] = None
    year: Optional[str] = None
    semester: Optional[int] = None

class RAGSearchRequest(BaseModel):
    query: str = Field(..., description="Semantic search query")
    department: str = Field(default="CSE")
    collection: Optional[str] = Field(default=None)
    top_k: int = Field(default=4)

class FileProcessRequest(BaseModel):
    file_id: str = Field(..., description="MongoDB FileDocument ID")
    file_url: str = Field(..., description="ImageKit URL or local URL")
    filename: str = Field(..., description="Original filename")
    mime_type: str = Field(default="", description="MIME type")
    file_type: str = Field(default="", description="Detected file type")
    user_id: str = Field(default="", description="User ID")
    conversation_id: Optional[str] = Field(default=None)
    department_id: Optional[str] = Field(default=None)
    role: str = Field(default="student")
    local_path: Optional[str] = Field(default=None, description="Local path to file if available")

# ----------------- Routes -----------------

@app.get("/")
def root():
    return {
        "service": "CSE Department AI Agentic Microservice",
        "department": "Computer Science & Engineering",
        "status": "Online",
        "docs": "/docs",
        "vector_engine": "Qdrant Cloud / Embedded (768 Dimensions)",
        "long_term_memory": "Qdrant (erp_long_term_memory)",
        "document_rag": "Qdrant (erp_documents)",
        "scheduling_engine": "Deterministic Constraint Optimization Engine (CSP)",
        "memory": "MongoDB Short-Term Memory (STM)",
        "academic_source_of_truth": "PostgreSQL"
    }

@app.get("/health")
def health_check():
    db_type, conn = postgres_tools._get_connection()
    pg_active = conn is not None
    if conn:
        try:
            conn.close()
        except Exception:
            pass

    return {
        "status": "UP",
        "service": "FastAPI AI Microservice",
        "qdrant_status": "Ready",
        "qdrant_collections": ["erp_long_term_memory", "erp_documents", "Notes", "Circulars"],
        "mongo_status": "Ready" if mongo_memory.client else "Cache Mode",
        "postgresql_status": f"Ready ({db_type})" if pg_active else "Unavailable",
        "database": "postgresql",
        "llm_provider": llm_provider.__class__.__name__,
        "llm_configured": llm_provider.is_configured(),
        "active_agents": [
            "ERPAssistantAgent",
            "TimetableAgent",
            "TeacherSchedulingAgent",
            "TeacherAbsenceAgent",
            "AttendanceAgent",
            "LeaveManagementAgent",
            "AcademicInformationAgent",
            "RAGAgent",
            "ReportingAgent",
            "FileGenerationAgent"
        ]
    }

@app.get("/health/db")
def health_db():
    db_type, conn = postgres_tools._get_connection()
    active = conn is not None
    if conn:
        try:
            conn.close()
        except Exception:
            pass
    return {
        "status": "UP" if active else "DOWN",
        "database": "postgresql",
        "dialect": db_type,
        "mongo_connected": mongo_memory.client is not None
    }

@app.get("/health/qdrant")
def health_qdrant():
    try:
        collections = [c.name for c in qdrant_manager.client.get_collections().collections]
        return {"status": "UP", "engine": "Qdrant", "collections": collections}
    except Exception as e:
        return {"status": "DEGRADED", "error": str(e), "engine": "Qdrant"}

@app.get("/health/ai")
def health_ai():
    return {
        "status": "UP",
        "llm_provider": llm_provider.__class__.__name__,
        "llm_configured": llm_provider.is_configured(),
        "embedding_provider": "LocalDenseEmbedding (768-dim L2 Normalized)",
        "orchestrator": "CentralAgentOrchestrator"
    }

@app.post("/ai/chat")
async def chat_endpoint(req: ChatRequest):
    """
    Central Multi-Agent Chat Entrypoint.
    Executes CentralAgentOrchestrator pipeline (Intent Detection -> Selective Agent Selection -> Tool Execution).
    """
    try:
        user_role = (req.role or "student").lower()
        query_text = (req.prompt or req.message or "").strip()
        conv_id = req.conversation_id or req.conversationId or f"conv_{int(datetime.utcnow().timestamp())}"
        target_agent = (req.agent or "").lower()

        if not query_text:
            raise HTTPException(status_code=400, detail="A message or prompt text is required.")

        # Save user message to MongoDB STM
        mongo_memory.save_message(
            conversation_id=conv_id,
            user_id=req.user_id,
            role=user_role,
            sender="user",
            content=query_text
        )

        # Execute selective agent orchestration
        result = central_orchestrator.orchestrate(
            prompt=query_text,
            user_id=req.user_id,
            role=user_role,
            conversation_id=conv_id,
            target_agent=target_agent,
            context_history=req.context_history
        )

        return result
    except Exception as e:
        logger.error(f"[Chat Endpoint Error]: {e}")
        raise HTTPException(status_code=500, detail=f"AI Agent execution error: {str(e)}")

@app.post("/ai/chat/stream")
async def chat_stream_endpoint(req: ChatRequest):
    """
    Streaming Chat Endpoint utilizing the active LLM Provider's stream generator.
    """
    from fastapi.responses import StreamingResponse

    user_role = (req.role or "student").lower()
    query_text = (req.prompt or req.message or "").strip()

    if not query_text:
        raise HTTPException(status_code=400, detail="A message or prompt text is required.")

    messages = [{"role": "system", "content": f"You are the CSE Department ERP Assistant for a {user_role}."},
                {"role": "user", "content": query_text}]

    def token_stream():
        for token in llm_provider.generate_stream(messages):
            yield f"data: {token}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(token_stream(), media_type="text/event-stream")


# ----------------- Dedicated Timetable & Scheduler API -----------------

@app.post("/ai/timetable/generate")
async def generate_timetable_api(req: GenerateTimetableRequest):
    """
    Deterministic Timetable Generator Endpoint:
    Queries authoritative PostgreSQL tables -> executes CSP constraint optimizer -> saves new version in PostgreSQL -> outputs XLSX & PDF.
    """
    try:
        subjects = postgres_tools.get_all_subjects(semester=req.semester, department=req.department)
        faculty_list = postgres_tools.get_all_faculty(department=req.department)
        rooms = postgres_tools.get_all_rooms(department=req.department)

        opt_res = scheduler_optimizer.generate_timetable(
            department=req.department,
            year=req.year,
            semester=req.semester,
            section=req.section,
            subjects=subjects,
            faculty_list=faculty_list,
            rooms=rooms,
            custom_constraints=req.custom_constraints,
            custom_subjects=req.custom_subjects,
            period_timings=req.period_timings,
            start_time=req.start_time,
            period_duration_minutes=req.period_duration_minutes,
            periods_per_day=req.periods_per_day,
            working_days=req.working_days
        )

        slots = opt_res.get("timetable_slots", [])
        metrics = opt_res.get("metrics", {})

        # Save to PostgreSQL
        master_id = postgres_tools.save_new_timetable_version(
            department=req.department,
            year=req.year,
            semester=req.semester,
            section=req.section,
            academic_year=req.academic_year,
            slots=slots,
            stats=metrics,
            created_by=req.created_by
        )

        master_row = postgres_tools.get_timetable_master(req.semester, req.section, req.academic_year)
        version_num = master_row.get("version", 1) if master_row else 1

        excel_info = timetable_file_generator.generate_excel(
            req.department, req.year, req.semester, req.section, req.academic_year, version_num, slots, metrics
        )
        pdf_info = timetable_file_generator.generate_pdf(
            req.department, req.year, req.semester, req.section, req.academic_year, version_num, slots, metrics
        )

        return {
            "success": True,
            "master_id": master_id,
            "version": version_num,
            "department": req.department,
            "year": req.year,
            "semester": req.semester,
            "section": req.section,
            "slots_count": len(slots),
            "metrics": metrics,
            "conflicts": opt_res.get("conflicts", []),
            "files": {
                "excel": excel_info,
                "pdf": pdf_info
            },
            "slots": slots
        }
    except Exception as e:
        logger.error(f"[Generate Timetable API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/teacher-scheduler/analyze")
async def analyze_absence_api(req: AnalyzeAbsenceRequest):
    """
    Teacher Absence & Substitution Analysis Endpoint:
    Finds affected classes for absent faculty and ranks feasible substitutes deterministically.
    """
    try:
        res = absence_adjuster.analyze_and_propose(
            teacher_query=req.teacher_name,
            date_str=req.date,
            day_name=req.day,
            department=req.department
        )
        return res
    except Exception as e:
        logger.error(f"[Analyze Absence API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/teacher-scheduler/apply")
async def apply_substitutions_api(req: ApplySubstitutionRequest):
    """
    Applies approved substitution proposals transactionally into PostgreSQL.
    """
    try:
        res = absence_adjuster.execute_approved_substitutions(
            absence_data=req.absence_data,
            approved_by=req.approved_by
        )
        return res
    except Exception as e:
        logger.error(f"[Apply Substitutions API Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/timetable/export/excel")
async def export_excel_api(req: ExportTimetableRequest):
    slots = postgres_tools.get_timetable(year=req.year, semester=req.semester, section=req.section)
    res = timetable_file_generator.generate_excel(
        req.department, req.year, req.semester, req.section, req.academic_year, req.version, slots
    )
    return {"success": True, **res}

@app.post("/ai/timetable/export/pdf")
async def export_pdf_api(req: ExportTimetableRequest):
    slots = postgres_tools.get_timetable(year=req.year, semester=req.semester, section=req.section)
    res = timetable_file_generator.generate_pdf(
        req.department, req.year, req.semester, req.section, req.academic_year, req.version, slots
    )
    return {"success": True, **res}

# ----------------- Document RAG Indexing & Retrieval -----------------

@app.post("/ai/rag/index")
async def index_document_endpoint(req: IndexDocumentRequest):
    """
    Ingests document into Qdrant erp_documents with department isolation.
    """
    try:
        if not os.path.exists(req.filePath):
            raise HTTPException(status_code=404, detail=f"File not found on server: {req.filePath}")

        raw_text = document_processor.extract_text(req.filePath)
        if not raw_text or not raw_text.strip():
            raw_text = f"Title: {req.title}\nCategory: {req.category}\nDepartment: Computer Science & Engineering"

        metadata = {
            "title": req.title,
            "category": req.category,
            "note_id": req.noteId,
            "file_name": req.fileName or os.path.basename(req.filePath),
            "subject_id": req.subjectId,
            "year": req.year,
            "semester": req.semester,
            "department": "CSE"
        }
        chunks = document_processor.chunk_text(raw_text, metadata=metadata)
        count = qdrant_manager.index_document_chunks(collection_name="erp_documents", chunks=chunks)

        return {
            "success": True,
            "message": f"Successfully indexed {count} chunks into Qdrant 'erp_documents'.",
            "chunksIndexed": count,
            "collection": "erp_documents",
            "title": req.title
        }
    except Exception as e:
        logger.error(f"[RAG Index Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ai/rag/search")
async def rag_search_endpoint(req: RAGSearchRequest):
    """
    Performs hybrid retrieval against Qdrant erp_documents with department isolation.
    """
    try:
        results = qdrant_manager.search_rag(
            query=req.query,
            department=req.department,
            category=req.collection,
            top_k=req.top_k
        )
        return {
            "success": True,
            "query": req.query,
            "department": req.department,
            "results": results
        }
    except Exception as e:
        logger.error(f"[RAG Search Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ----------------- Universal File Processing Pipeline -----------------

@app.post("/ai/files/process")
async def process_file_endpoint(req: FileProcessRequest, background_tasks: BackgroundTasks):
    """
    Universal File Processing Pipeline entry point.
    Receives file metadata from Node.js backend, processes asynchronously.
    """
    try:
        logger.info(f"[File Process] Received: {req.filename} (type={req.file_type}, id={req.file_id})")

        # Process in background to not block the response
        background_tasks.add_task(
            _background_process_file,
            file_id=req.file_id,
            file_url=req.file_url,
            filename=req.filename,
            mime_type=req.mime_type,
            file_type=req.file_type,
            user_id=req.user_id,
            conversation_id=req.conversation_id,
            department_id=req.department_id,
            role=req.role,
            local_path=req.local_path
        )

        return {
            "success": True,
            "message": f"File '{req.filename}' queued for processing.",
            "file_id": req.file_id,
            "status": "processing"
        }
    except Exception as e:
        logger.error(f"[File Process Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))


async def _background_process_file(
    file_id: str,
    file_url: str,
    filename: str,
    mime_type: str,
    file_type: str,
    user_id: str,
    conversation_id: str,
    department_id: str,
    role: str,
    local_path: Optional[str] = None
):
    """Background task for file processing."""
    try:
        result = await file_type_router.process_file(
            file_id=file_id,
            file_url=file_url,
            filename=filename,
            mime_type=mime_type,
            file_type=file_type,
            user_id=user_id,
            conversation_id=conversation_id or "",
            department_id=department_id or "",
            role=role,
            local_path=local_path
        )
        logger.info(f"[File Process] Completed: {filename} -> {result.get('chunks_indexed', 0)} chunks indexed")
    except Exception as e:
        logger.error(f"[File Process Background Error] {filename}: {e}")


@app.get("/ai/files/{file_id}/content")
async def get_file_content(file_id: str):
    """
    Get processed/normalized content for a file.
    Useful for agents that need to reason over file content.
    """
    try:
        # Search Qdrant for chunks belonging to this document
        results = qdrant_manager.search_rag(
            query="document content",
            department="CSE",
            top_k=20
        )

        # Filter results for this specific document
        doc_chunks = []
        for r in results:
            meta = r.get("metadata", {})
            if meta.get("document_id") == file_id:
                doc_chunks.append({
                    "content": r.get("snippet", ""),
                    "section": meta.get("section", "General"),
                    "page": meta.get("page"),
                    "chunk_id": meta.get("chunk_id", 0)
                })

        return {
            "success": True,
            "file_id": file_id,
            "chunks": doc_chunks,
            "chunk_count": len(doc_chunks)
        }
    except Exception as e:
        logger.error(f"[File Content Error]: {e}")
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
