// ============================================================================
// CampusFlow CSE Department ERP - RBAC Permissions Matrix
// Canonical Source of Truth for Role-Based Access Control
// ============================================================================

const PERMISSIONS = {
  // User Management
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  PASSWORD_RESET: 'PASSWORD_RESET',

  // Institutional Management
  DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',
  FACULTY_MANAGE: 'FACULTY_MANAGE',
  HOD_ASSIGN: 'HOD_ASSIGN',
  HOD_REMOVE: 'HOD_REMOVE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  SYSTEM_CONFIG: 'SYSTEM_CONFIG',

  // Academic & Scheduling
  TIMETABLE_VIEW: 'TIMETABLE_VIEW',
  TIMETABLE_MANAGE: 'TIMETABLE_MANAGE',
  TIMETABLE_GENERATE: 'TIMETABLE_GENERATE',
  TIMETABLE_PUBLISH: 'TIMETABLE_PUBLISH',
  SUBJECT_MANAGE: 'SUBJECT_MANAGE',

  // Attendance
  ATTENDANCE_READ_SELF: 'ATTENDANCE_READ_SELF',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  ATTENDANCE_VIEW_ALL: 'ATTENDANCE_VIEW_ALL',
  ATTENDANCE_OVERRIDE: 'ATTENDANCE_OVERRIDE',
  ATTENDANCE_QUERY_SUBMIT: 'ATTENDANCE_QUERY_SUBMIT',
  ATTENDANCE_QUERY_REVIEW: 'ATTENDANCE_QUERY_REVIEW',
  ATTENDANCE_QUERY_APPROVE: 'ATTENDANCE_QUERY_APPROVE',
  ATTENDANCE_CONSIDERATION_SUBMIT: 'ATTENDANCE_CONSIDERATION_SUBMIT',
  ATTENDANCE_CONSIDERATION_REVIEW: 'ATTENDANCE_CONSIDERATION_REVIEW',
  ATTENDANCE_CONSIDERATION_APPROVE: 'ATTENDANCE_CONSIDERATION_APPROVE',

  // Leave Management
  LEAVE_APPLY: 'LEAVE_APPLY',
  LEAVE_REVIEW_TG: 'LEAVE_REVIEW_TG',
  LEAVE_APPROVE_HOD: 'LEAVE_APPROVE_HOD',

  // Student & Mentor Management
  STUDENT_PROFILE_READ: 'STUDENT_PROFILE_READ',
  STUDENT_LIST_VIEW: 'STUDENT_LIST_VIEW',
  MENTEE_MONITOR: 'MENTEE_MONITOR',

  // Reporting
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_GENERATE: 'REPORT_GENERATE',

  // AI & Assistant
  AI_CHAT: 'AI_CHAT',
  AI_TOOLS_EXECUTE: 'AI_TOOLS_EXECUTE'
};

const ROLE_PERMISSIONS = {
  student: [
    PERMISSIONS.STUDENT_PROFILE_READ,
    PERMISSIONS.ATTENDANCE_READ_SELF,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ATTENDANCE_QUERY_SUBMIT,
    PERMISSIONS.ATTENDANCE_CONSIDERATION_SUBMIT,
    PERMISSIONS.AI_CHAT
  ],

  faculty: [
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.STUDENT_LIST_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_EXECUTE
  ],

  teacher: [
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.STUDENT_LIST_VIEW,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_EXECUTE
  ],

  tg: [
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.STUDENT_LIST_VIEW,
    PERMISSIONS.MENTEE_MONITOR,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_REVIEW_TG,
    PERMISSIONS.ATTENDANCE_QUERY_REVIEW,
    PERMISSIONS.ATTENDANCE_CONSIDERATION_REVIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_EXECUTE
  ],

  hod: [
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.SUBJECT_MANAGE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.TIMETABLE_MANAGE,
    PERMISSIONS.TIMETABLE_GENERATE,
    PERMISSIONS.TIMETABLE_PUBLISH,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_OVERRIDE,
    PERMISSIONS.ATTENDANCE_QUERY_APPROVE,
    PERMISSIONS.ATTENDANCE_CONSIDERATION_APPROVE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_APPROVE_HOD,
    PERMISSIONS.STUDENT_LIST_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_EXECUTE
  ],

  admin: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.PASSWORD_RESET,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.SUBJECT_MANAGE,
    PERMISSIONS.HOD_ASSIGN,
    PERMISSIONS.HOD_REMOVE,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.TIMETABLE_MANAGE,
    PERMISSIONS.TIMETABLE_GENERATE,
    PERMISSIONS.TIMETABLE_PUBLISH,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_APPROVE_HOD,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.STUDENT_LIST_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_TOOLS_EXECUTE
  ]
};

function getPermissionsForRole(role) {
  const norm = (role || '').toLowerCase();
  return ROLE_PERMISSIONS[norm] || [];
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole
};
